#ifndef CONFIG_H
#define CONFIG_H

// ===== MOTOR DRIVER =====
#define MOTOR_LEFT_PWM 25
#define MOTOR_RIGHT_PWM 26

// ===== ULTRASONIC SENSOR =====
#define ULTRASONIC_TRIG 33
#define ULTRASONIC_ECHO 32

// ===== LINEAR ACTUATOR (BTS7960) =====
#define ACTUATOR_RPWM 27
#define ACTUATOR_LPWM 14

// ===== STEPPER MOTOR (ULN2003) =====
#define STEPPER_IN1 18
#define STEPPER_IN2 19
#define STEPPER_IN3 21
#define STEPPER_IN4 22

#endif